language: java
jdk:
  -openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x ./gradlew
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-web *
  - mkdir -p deploy
  - mv springboot-web.zip deploy/springboot-web.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-web-yjh-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECREY_KEY
    bucket: springboot-web-yjh-build
    key: springboot-web.zip
    bundle-type: zip
    application: springboot-web
    deployment-group: springboot-web-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - dddalang4@naver.com